version: '3.7'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongo
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_URI: mongodb://127.0.0.1:27017/?directConnection=true

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
